services:

  pg:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - shop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d auth" ]
      interval: 2s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - shop
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:6379"

  app:
    networks:
      - shop
    image: fastapi:latest
    ports:
      - "8000:${APP_PORT}"
    env_file:
      - .env
    environment:
      - DB__URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pg:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      pg:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn main:main_app --host ${APP_HOST} --port ${APP_PORT}"
    restart: unless-stopped

networks:
  shop:
    driver: bridge

volumes:
  pg_data:
